name: ConvertCVPDFToPNG

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install pdftoppm
        run: sudo apt-get install poppler-utils -y

      - name: Convert pdf to img
        run: pdftoppm $GITHUB_WORKSPACE/AlexOgilvieResume.pdf AlexOgilvieResume -png -f 1 -singlefile

      - uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
